<?php
    /** @var \Magento\Catalog\Api\Data\ProductSearchResultsInterface $products */
    $products = $block->getProducts();
?>

<?php if ($products->getTotalCount()):?>

    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    $image = 'new_products_content_widget_grid';
    $title = '';
    $items = $products->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>

    <div class="block widget block-products-list <?php echo $mode; ?>">
        <?php if ($title):?>
            <div class="block-title">
                <strong><?php echo $title; ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
                <ol class="product-items <?php echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $item): ?>
                        <?php echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?php echo $block->getProductUrl($item) ?>" class="product-item-photo">
                                <?php echo $imageBlock->init($item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($item->getName()) ?>"
                                       href="<?php echo $block->getProductUrl($item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($item->getName()) ?>
                                    </a>
                                </strong>
                                <?php
                                echo $block->getProductPriceHtml($item, $type);
                                ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($item->isSaleable()): ?>
                                                    <?php if ($item->getTypeInstance()->hasRequiredOptions($item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($item) ?>"}}'
                                                                type="button" title="<?php echo __('Add to Cart') ?>">
                                                            <span><?php echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($item), ['product' => $item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php echo $postData; ?>'
                                                                type="button" title="<?php echo __('Add to Cart') ?>">
                                                            <span><?php echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?php echo $block->getAddToWishlistParams($item); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?php echo __('Add to Wish List') ?>">
                                                        <span><?php echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?php echo $compareHelper->getPostDataParams($item);?>'
                                                       title="<?php echo __('Add to Compare') ?>">
                                                        <span><?php echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php else: ?>
    <?php echo __('Products not found.') ?>
<?php endif;?>